package View.LogInView;

import Controller.Controller;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Locale;

public class SignUpIn extends JDialog implements ActionListener {
    private JTextField tfEMail;
    private JPasswordField pfPasswordSignIn;
    private JTextField tfFName;
    private JTextField tfLName;
    private JPasswordField pfpasswordSignUp;
    private JComboBox cBoxRole;
    private JTextField tfEMailSignUP;
    private JButton btnSignIn;
    private JButton btnsignUp;
    private JPanel signInPanel;
    private JPanel signUpPanel;
    private Controller controller;


    /**
     * @param controller Instantiate the form
     */
    public SignUpIn(Controller controller) {
        this.controller = controller;

        JFrame   frame = new JFrame("Bugtracker Log In");
        frame.setSize(new Dimension(400, 500));
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);




        frame.pack();
        frame.setVisible(true);

    }


    public void addActionListerner(JButton btn) {
        btn.addActionListener(this);
    }


    @Override
    public void actionPerformed(ActionEvent e) {

        if (e.getSource() == btnsignUp) {
            controller.onSignUpBtnClick();
        }
        if (e.getSource() == btnSignIn) {
            controller.onSignInBtnClick();
        }
    }

    //getters for controller-class to get values later
    public JTextField getTfEMail() {
        return tfEMail;
    }

    public JPasswordField getPfPasswordSignIn() {
        return pfPasswordSignIn;
    }

    public JTextField getTfFName() {
        return tfFName;
    }

    public JTextField getTfLName() {
        return tfLName;
    }

    public JPasswordField getPfpasswordSignUp() {
        return pfpasswordSignUp;
    }

    public JComboBox getcBoxRole() {
        return cBoxRole;
    }

    public JTextField getTfEMailSignUP() {
        return tfEMailSignUP;
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        signInPanel = new JPanel();
        signInPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(9, 8, new Insets(0, 0, 0, 0), -1, -1));
        signInPanel.setBackground(new Color(-16748046));
        Font signInPanelFont = this.$$$getFont$$$("Arial", -1, -1, signInPanel.getFont());
        if (signInPanelFont != null) signInPanel.setFont(signInPanelFont);
        signUpPanel = new JPanel();
        signUpPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(8, 8, new Insets(0, 0, 0, 0), -1, -1));
        signUpPanel.setBackground(new Color(-859740));
        signInPanel.add(signUpPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 7, 9, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$("Arial Black", -1, -1, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setForeground(new Color(-5921893));
        label1.setText("Create New User");
        signUpPanel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 8, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tfFName = new JTextField();
        Font tfFNameFont = this.$$$getFont$$$("Arial", -1, -1, tfFName.getFont());
        if (tfFNameFont != null) tfFName.setFont(tfFNameFont);
        tfFName.setForeground(new Color(-4075819));
        tfFName.setText("First name");
        signUpPanel.add(tfFName, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 8, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        tfLName = new JTextField();
        Font tfLNameFont = this.$$$getFont$$$("Arial", -1, -1, tfLName.getFont());
        if (tfLNameFont != null) tfLName.setFont(tfLNameFont);
        tfLName.setForeground(new Color(-4075819));
        tfLName.setText("Last name");
        signUpPanel.add(tfLName, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 8, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        signUpPanel.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(7, 4, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        pfpasswordSignUp = new JPasswordField();
        Font pfpasswordSignUpFont = this.$$$getFont$$$("Arial", -1, -1, pfpasswordSignUp.getFont());
        if (pfpasswordSignUpFont != null) pfpasswordSignUp.setFont(pfpasswordSignUpFont);
        pfpasswordSignUp.setForeground(new Color(-4075819));
        pfpasswordSignUp.setText("Password");
        signUpPanel.add(pfpasswordSignUp, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 8, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        cBoxRole = new JComboBox();
        Font cBoxRoleFont = this.$$$getFont$$$("Arial", -1, -1, cBoxRole.getFont());
        if (cBoxRoleFont != null) cBoxRole.setFont(cBoxRoleFont);
        cBoxRole.setForeground(new Color(-4075819));
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("User");
        defaultComboBoxModel1.addElement("Admin");
        defaultComboBoxModel1.addElement("Agent");
        cBoxRole.setModel(defaultComboBoxModel1);
        signUpPanel.add(cBoxRole, new com.intellij.uiDesigner.core.GridConstraints(6, 0, 1, 5, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setHorizontalAlignment(2);
        label2.setHorizontalTextPosition(2);
        label2.setIcon(new ImageIcon(getClass().getResource("/BugTrckerLogo.png")));
        label2.setText("");
        signUpPanel.add(label2, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 8, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tfEMailSignUP = new JTextField();
        Font tfEMailSignUPFont = this.$$$getFont$$$("Arial", -1, -1, tfEMailSignUP.getFont());
        if (tfEMailSignUPFont != null) tfEMailSignUP.setFont(tfEMailSignUPFont);
        tfEMailSignUP.setForeground(new Color(-4075819));
        tfEMailSignUP.setText("E-mail");
        signUpPanel.add(tfEMailSignUP, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 8, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
        signUpPanel.add(spacer2, new com.intellij.uiDesigner.core.GridConstraints(7, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        btnsignUp = new JButton();
        Font btnsignUpFont = this.$$$getFont$$$("Arial", -1, -1, btnsignUp.getFont());
        if (btnsignUpFont != null) btnsignUp.setFont(btnsignUpFont);
        btnsignUp.setForeground(new Color(-4075819));
        btnsignUp.setText("Sign Up");
        signUpPanel.add(btnsignUp, new com.intellij.uiDesigner.core.GridConstraints(7, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer3 = new com.intellij.uiDesigner.core.Spacer();
        signUpPanel.add(spacer3, new com.intellij.uiDesigner.core.GridConstraints(7, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer4 = new com.intellij.uiDesigner.core.Spacer();
        signUpPanel.add(spacer4, new com.intellij.uiDesigner.core.GridConstraints(7, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        tfEMail = new JTextField();
        Font tfEMailFont = this.$$$getFont$$$("Arial", -1, -1, tfEMail.getFont());
        if (tfEMailFont != null) tfEMail.setFont(tfEMailFont);
        tfEMail.setForeground(new Color(-4075819));
        tfEMail.setText("E-mail");
        signInPanel.add(tfEMail, new com.intellij.uiDesigner.core.GridConstraints(4, 1, 1, 5, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        pfPasswordSignIn = new JPasswordField();
        Font pfPasswordSignInFont = this.$$$getFont$$$("Arial", -1, -1, pfPasswordSignIn.getFont());
        if (pfPasswordSignInFont != null) pfPasswordSignIn.setFont(pfPasswordSignInFont);
        pfPasswordSignIn.setForeground(new Color(-4075819));
        pfPasswordSignIn.setText("Password");
        signInPanel.add(pfPasswordSignIn, new com.intellij.uiDesigner.core.GridConstraints(5, 1, 1, 5, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer5 = new com.intellij.uiDesigner.core.Spacer();
        signInPanel.add(spacer5, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer6 = new com.intellij.uiDesigner.core.Spacer();
        signInPanel.add(spacer6, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 4, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer7 = new com.intellij.uiDesigner.core.Spacer();
        signInPanel.add(spacer7, new com.intellij.uiDesigner.core.GridConstraints(4, 6, 2, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        btnSignIn = new JButton();
        Font btnSignInFont = this.$$$getFont$$$("Arial", -1, -1, btnSignIn.getFont());
        if (btnSignInFont != null) btnSignIn.setFont(btnSignInFont);
        btnSignIn.setForeground(new Color(-4075819));
        btnSignIn.setText("Sign In");
        signInPanel.add(btnSignIn, new com.intellij.uiDesigner.core.GridConstraints(7, 3, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer8 = new com.intellij.uiDesigner.core.Spacer();
        signInPanel.add(spacer8, new com.intellij.uiDesigner.core.GridConstraints(8, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return signInPanel;
    }
}




